A/A/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) #remove this for productions

A/accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'
urlpatterns = [
    path('register/', views.UserRegisterView.as_view(), name='user_register'),
    path('verify/', views.UserRegisterVerifyCodeView.as_view(), name='verify_code'),
    path('login/', views.UserLoginView.as_view(), name='user_login'),
    path('logout/', views.UserLogoutView.as_view(), name='user_logout'),
]

A/home/urls.py
from django.urls import path
from . import views
from .views import ProductDetailView

app_name = 'home'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('<slug:slug>/', ProductDetailView.as_view(), name='product_detail'),
]

A/templates/inc/messages.html
{% if messages %}
    {% for msg in messages %}
        <p class="alert alert-{{ msg.tags }}">{{ msg }}</p>
    {% endfor %}
{% endif %}

A/templates/inc/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'home:home' %}">Online Shop</a>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                {% if request.user.is_authenticated %}
                    <a class="nav-link active" aria-current="page" href="#">Profile</a>
                    <a class="nav-link active " aria-current="page" href="{% url 'accounts:user_logout' %}">Logout</a>
                {% else %}
                    <a class="nav-link active " aria-current="page" href="{% url 'accounts:user_login' %}">Login</a>
                    <a class="nav-link active " aria-current="page" href="{% url 'accounts:user_register' %}">Register</a>
                {% endif %}
            </div>
        </div>class="navbar-text fw-bold"
        <div class="ms-auto">
            {% if request.user.is_authenticated %}
                <a class="navbar-text fw-bold text-decoration-none" href="#">
                    {{ request.user.full_name }}
                </a>
            {% endif %}
        </div>
    </div>
</nav>